export const performLogin = async () => {
    try {
        // let random = Math.random();
        // if (random % 2) {
            return { success: true }
        // } else {
        //     throw new Error('Error Logging In')
        // }
    } catch (err) {
        throw err;
    }
}

export const registerUser = async () => {
    try {
        // let random = Math.random();
        // if (random % 2) {
            return { success: true }
        // } else {
        //     throw new Error('Error Registering User')
        // }
    } catch (err) {
        throw err;
    }
}

export const getCurrentUser = async () => {
    try {
        // let random = Math.random();
        // if (random % 2) {
            return { success: true }
        // } else {
        //     throw new Error('Error Getting Current User')
        // }
    } catch (err) {
        throw err;
    }
}